server: 
  port: 8081
  servlet: 
    context-path: /
    encoding: 
      charset: UTF-8
      enabled: true
      force: true
  
# db connection(oracle) - spring(context.xml)
spring:
  datasource:
    url: jdbc:oracle:thin:@forbidden.ceufyrm1vih9.ap-northeast-2.rds.amazonaws.com:1521/ORCL
    username: forbidden
    password: 12345678
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.example.team_pj_springboot.mappers